### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ghost** [MrEliptik/godot_experiments#9]
Hello without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by MrEliptik** [comment]
You're right! I'll make sure to add one soon. Do you have any suggestion? I think I want something very permissive, as it's mainly oriented towards sharing stuff.

**Comment by ghost** [comment]
The [MIT](https://choosealicense.com/licenses/mit/) license is a short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.
[Here](https://choosealicense.com/appendix/) is a table of popular licenses.

**Comment by MrEliptik** [comment]
Thank you for your response. I've chosen the MIT license, as it seems to be well suited for this project.
